include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    file_names: false
    require_trailing_commas: false
    prefer_constructors_over_static_methods: false
    constant_identifier_names: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    sort_pub_dependencies: false
    use_key_in_widget_constructors: false

    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
